# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kazuki Yamada
email: kaz.yamada@outlook.com
description: Student, developer, human being.

# the subpath of your site, e.g. /blog
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

# the base hostname & protocol for your site, e.g. http://example.com
url: "http://kaz-yamada.github.io"

# Site Author Information
author:
  name: "Kazuki Yamada"
  avatar: "https://avatars1.githubusercontent.com/u/20230684?v=4&u=3d6f9f3f0ba990545abac17e50369388c9722ebb&s=400"
  bio: "Just another developer in Sydney."
  email: 

# Social icons and sharing options
# name: Name of site
# icon: respective fontAwesome icon (remove the fa-)
# username: username for site (optional)
# url: link to profile page of site

social:
  - name: Facebook
    icon: facebook
    username:
    url: "https://www.facebook.com/kazadamay"

  - name: GitHub
    icon: github
    username: "kaz-yamada"
    url: "https://github.com/kaz-yamada/"

  - name: LinkedIn
    icon: linkedin
    username: "kaz-yamada"
    url: "https://www.linkedin.com/in/kaz-yamada/"
    
  - name: Stackoverflow
    icon: stack-overflow
    username:
    url: "https://stackoverflow.com/users/8009329/k-yamada"

  - name: Codepen
    icon: codepen
    username:
    url: "https://codepen.io/kaz-yamada/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate  
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
  - src
  - gulpfile.js
  - webpack.config.js
# sass:
#   sass_dir: src/_sass
#   style: compressed
include: ["_pages"]
kramdown:
  input: GFM
paginate: 9
paginate_path: "/blog/page:num/"
defaults:
  - values:
      layout: "page"

remote_theme: kazyamada/Cold_Sun